### ISSUE TITLE
Import Strava Archive

### ISSUE THREAD

**Issue by Hanfbaum** [martin-ueding/geo-activity-playground#140] opened 2024-08-06 08:23 UTC
Update Version 0.26 hat leider noch nicht alle Probleme mit dem Import aus einem Strava archive beseitigt.
""
E:\Martin\Playground_Strava>python -m geo_activity_playground serve
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 116, in <module>
    main()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 92, in main
    options.func(options)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 66, in <lambda>
    *make_activity_repository(options.basedir, options.skip_strava),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\__main__.py", line 110, in make_activity_repository
    scan_for_activities(repository, tile_visit_accessor, config, skip_strava)
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\webui\upload\controller.py", line 101, in scan_for_activities
    import_from_strava_checkout()
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\importers\strava_checkout.py", line 161, in import_from_strava_checkout
    activities_ids_to_parse = [
                              ^
  File "C:\Users\Hanfbaum\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\geo_activity_playground\importers\strava_checkout.py", line 164, in <listcomp>
    if not (activity_extracted_meta_dir() / f"{activity_id.pickle}").exists()
                                               ^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'pickle'

E:\Martin\Playground_Strava>pause
Drücken Sie eine beliebige Taste . . .

""

**Comment by martin-ueding** [comment] 2024-08-06 10:36
Duplicate of #139.

**Comment by martin-ueding** [comment] 2024-08-06 10:42
Will be fixed in 0.26.1 shortly.

**Closed by martin-ueding** 2024-08-06 10:42 UTC
Labels: type: bug, component: Strava, triage: duplicate

**Comment by Hanfbaum** [comment] 2024-08-06 11:53
Import läuft mit dem Update jetzt durch. Danach lädt er, aber noch mit der API sehr viel mehr als im Archive fehlen dürften. Das Programm scheint noch mal alle Aktivitäten dabei durch zugehen. Vor dem Update habe ich aber meine ich nur Zahlen unter 50 pro Timeout gesehen.
````
E:\Martin\Playground_Strava>python -m geo_activity_playground serve
Import from Strava export: 0it [00:00, ?it/s]
Downloading Strava activities: 0it [00:00, ?it/s]
2024-08-06 13:20:56 geo_activity_playground.importers.strava_api WARNING Strava rate limit exceeded, will try again at 2024-08-06T13:30:00.
Downloading Strava activities: 97it [01:19,  1.23it/s]
2024-08-06 13:31:29 geo_activity_playground.importers.strava_api WARNING Strava rate limit exceeded, will try again at 2024-08-06T13:45:00.
Downloading Strava activities: 94it [01:24,  1.11it/s]
2024-08-06 13:46:34 geo_activity_playground.importers.strava_api WARNING Strava rate limit exceeded, will try again at 2024-08-06T14:00:00.


````

**Comment by biker793** [comment] 2024-08-07 10:08
@Hanfbaum das ist wahrscheinlich der gleiche Fehler wie #128
