### ISSUE TITLE
Filenames with # are ignored on macOS

### ISSUE THREAD

**Issue by martin-ueding** [martin-ueding/geo-activity-playground#186] opened 2024-10-13 16:13 UTC

**Comment by PelikhanWebDev** [comment] 2024-10-15 18:45
Items including • are being ignored as well.

**Comment by PelikhanWebDev** [comment] 2024-10-24 19:03
Tried a Strava workout using a # today. Worked as well.
Therefore I cannot reproduce the issue and the ticket can be closed as far as I am concerned.

**Closed** 2024-10-25 16:57 UTC
Labels: type: bug, component: activity files
