### ISSUE TITLE
Improve processing of multi-track GPX files

### ISSUE THREAD

**Issue by ray66** [martin-ueding/geo-activity-playground#90] opened 2024-02-18 17:21 UTC
When a GPX file contains more than one track, these are processed as one single continuous track. The distance between the last point of a track and the first point of the following track is added to the total distance of the activity. A straight line between the two points is drawn on  the map. 

It would be nice if tracks would be kept separate for statistics and display. This would allow to have a single GPX file and a single activity per day even when two or more activity stages on the same day are separated from each other e.g. by a train or ferry trip.

**Comment by martin-ueding** [comment] 2024-02-23 07:58
A GPX file has a hierarchy of tracks, segments and points. You want to have the different tracks be split into separate activities? If so, how should the names be derived? From the activity path plus something like “track 1”, “track 2”? How would one know if one track is a cycle trip and the other track is a run?

Personally I have separate activity files for such parts of the day and therefore created #94 where I want to provide a combined view for all activities for one day. Your request seems to be the complement of that.

Removing the straight lines is easier. There is already the concept of jumps that occur when there are more than 30 seconds between the points. If you have intermediate train or ferry trips it should already remove those straight lines unless I forgot to honor them somewhere. Do you have an example where this has failed?

**Comment by ray66** [comment] 2024-02-23 10:16
> Personally I have separate activity files for such parts of the day and therefore created #94 where I want to provide a combined view for all activities for one day. Your request seems to be the complement of that.

I have one GPX file per day with a track per segment, e.g. one track for the ride from home to the local trains station and another track for the ride from the destination train station back home.

> Removing the straight lines is easier. There is already the concept of jumps that occur when there are more than 30 seconds between the points. If you have intermediate train or ferry trips it should already remove those straight lines unless I forgot to honor them somewhere. 

This would fit my needs but it does not work for my files.

> Do you have an example where this has failed?

The attached file is a striped down example of the above scenario: two short segments with a length of roughly 4kms,  distant 46km from each other. geo-activity-playground displays a straight line between the segments and a distance of 50km.  

[20100711short.gpx.gz](https://github.com/martin-ueding/geo-activity-playground/files/14384083/20100711short.gpx.gz)

![Bildschirmfoto_2024-02-23_11-13-20](https://github.com/martin-ueding/geo-activity-playground/assets/4647893/22f4476e-7d3e-4639-b099-809d63c1b340)

**Comment by martin-ueding** [comment] 2024-03-02 07:22
I've imported your activity into my test space. It does work with the explorer tiles, there is no straight line between the activities:

![Screenshot_20240302_082107](https://github.com/martin-ueding/geo-activity-playground/assets/976924/c3125f60-93a9-4210-b07a-8b90ad43085c)

But in the maps there is a straight line:

![Screenshot_20240302_082123](https://github.com/martin-ueding/geo-activity-playground/assets/976924/3af08341-1170-4256-97d8-6ffae3f934ce)

So the problem is that the segments are separated in the explorer tile computation, but they are not honored on the maps. That is something that I can fix.

**Comment by martin-ueding** [comment] 2024-03-02 07:33
That fixed it, will be released with the 0.20.0 release.

![Screenshot_20240302_082754](https://github.com/martin-ueding/geo-activity-playground/assets/976924/3dc301df-9af2-4e01-b08a-56db81629433)
![Screenshot_20240302_083250](https://github.com/martin-ueding/geo-activity-playground/assets/976924/09d860bf-2f8a-4a27-8102-32f658702671)

**Comment by martin-ueding** [comment] 2024-03-02 07:53
And also the length computation takes the jumps into account now.

![Screenshot_20240302_085307](https://github.com/martin-ueding/geo-activity-playground/assets/976924/ff960ee2-fb20-4a4e-b4b7-b2cdba65683a)

**Comment by martin-ueding** [comment] 2024-03-02 08:07
Ah, the graphs below were also broken. This is before:

![Screenshot_20240302_085749](https://github.com/martin-ueding/geo-activity-playground/assets/976924/7fe9b050-257d-46da-9e27-62455aa92039)

And this afterwards:

![Screenshot_20240302_090548](https://github.com/martin-ueding/geo-activity-playground/assets/976924/04e26bf8-543e-494d-84bc-95185d2ca67f)

And also the share picture needed some work. Before:

![sharepic-1](https://github.com/martin-ueding/geo-activity-playground/assets/976924/23e599ef-e803-4fa0-b1a0-77fd410d2341)

And now:

![sharepic-2](https://github.com/martin-ueding/geo-activity-playground/assets/976924/190423e6-9672-49da-91ab-47250f594bae)

I think those were all locations where it makes a difference. If I missed something, feel free to reopen this ticket.

**Closed by martin-ueding** 2024-03-02 08:07 UTC
Labels: type: bug, status: in progress, status: ready for release, component: web UI

**Comment by martin-ueding** [comment] 2024-03-02 10:30
Version 0.20.0 is released you can update and try it out. If the issue persists, please reopen this ticket.
